### ISSUE TITLE
(node:22394) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by davidtorroija** [cascornelissen/event-hooks-webpack-plugin#3]
I'm receiving this warning 
(node:22394) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

so maybe this going to be a problem in future versions of webpack

**Comment by cascornelissen** [comment]
Yeah, this might require an update to this plugin... Would you be willing to submit a PR for this?

**Comment by cascornelissen** [comment]
@davidtorroija, I just tested this plugin against `webpack@5.0.0-alpha.11` and I'm not seeing any of the deprecation warnings you've listed so I'm guessing we're good. Could it be that another plugin was throwing this warning on your end?
