### ISSUE TITLE
Accessing errors in `done` event

### ISSUE THREAD

**Issue by mikeerickson** [cascornelissen/event-hooks-webpack-plugin#4]
Hey there

This plugin is doing almost exactly as I want.  However, I am trying to figure out how to get at the `stats` error list, but I am not having much success

My setup is as follows

```js
new EventHooksPlugin({
        done: stats => {
          console.log(stats) // <-- need to access the stats.errors here but it is always `undefined`
          exec('./tasks/build.sh', (err, stdout, stderr) => {
            if (stdout) process.stdout.write(stdout)
            if (stderr) process.stderr.write(stderr)
          })
        }
      })
```

The webpack docs state the `stats` response should include `errors` object, but again, it is undefined

[Done callback includes `stats`](https://webpack.js.org/api/compiler-hooks/#done)

[Stats Object should include errors](https://webpack.js.org/api/stats/#structure)

I have logged the `stats` result, but it does not include any `errors` object?

What I am specifically looking for is the ability to call my `exec` script ONLY if the compiler did not have any errors.  Is there another way of getting this to happen

**Comment by cascornelissen** [comment]
I'm guessing this is caused by the fact that `done` is an `AsyncSeriesHook`. Have you tried using an [asynchronous method](https://github.com/cascornelissen/event-hooks-webpack-plugin#asynchronous-usage)?

**Comment by mikeerickson** [comment]
@cascornelissen Thank you for the lead.  Using the asynchronous method, I have managed to extract the data I am looking for and all is good now.
