### ISSUE TITLE
beforeCompile hook gets called twice at the start

### ISSUE THREAD

**Issue by marcofugaro** [cascornelissen/event-hooks-webpack-plugin#6]
Hey, I love this plugin.

Do you have any idea why the beforeCompile hook gets called twice at the start?

I have this config

```js
module.exports = {
  watch: true,
  stats: false,
  plugins: [
    new EventHooksPlugin({
      beforeCompile() {
        console.log('⏳  Compiling...')
      },
  ],
}
```

And each time I start the application, it gets called twice. Is this webpack's fault?

<img width="169" alt="Screenshot 2020-04-27 at 19 05 48" src="https://user-images.githubusercontent.com/7217420/80399822-1c669180-88ba-11ea-85a9-f85a4ed8c981.png">

**Comment by cascornelissen** [comment]
If I change the [simple example](https://github.com/cascornelissen/event-hooks-webpack-plugin/tree/master/examples/simple) to `console.log()` on the `beforeCompile` hook it logs just once so it's unrelated to the plugin and probably also unrelated to Webpack (unless we're running different versions).

It's probably related to the custom wrapper around Webpack that you're running (if any, looks like it from the config you posted).

**Comment by marcofugaro** [comment]
Yeah probably. Anyway solved using the [compile](https://webpack.js.org/api/compiler-hooks/#compile) hook instead 🙌
