### ISSUE TITLE
How to log after the last webpack output line?

### ISSUE THREAD

**Issue by d9k** [cascornelissen/event-hooks-webpack-plugin#8]
I tried to add hook with `event-hooks-webpack-plugin` on `done` event.

This hook prints the log line but my log line isn't the last line in the output. 
he assets table and build warnings come after log line produced by my `EventHooksPlugin` instance;

My `EventHooksPlugin` instance is the last in `plugins:` webpack config section.

```
new EventHooksPlugin({
    done: () => {
        console.log('__TEST__ done');
    },
}),
```

How can I change code to ensure my `'__TEST__ done'` line is last in entire webpack output?

**Comment by d9k** [comment]
Solved with

```
    process.on('exit', function () {
        console.log('__TEST__ on process exit');
    });
```

**Comment by cascornelissen** [comment]
@d9k, yeah, AFAIK there's no hook that gets executed after the stats are printed. Your solution using `process.on('exit')` seems like a viable workaround 👍
